### PR TITLE
Update Drupal Version

### PR DESCRIPTION
**Pull request by smirfolio**
Security issue : https://www.drupal.org/SA-CORE-2018-004

### CODE REVIEW

**Review by ymarcon — CHANGES_REQUESTED** [review]
Rename drupal-7.58.sql to drupal-7.59.sql

**Comment by ymarcon** [comment]
Or the drupal-xxx.sql file is removed?

**Comment by smirfolio** [comment]
drupal-7.59.sql added

**Comment by ymarcon** [comment]
drupal-7.59.sql missing

**Comment by smirfolio** [comment]
@ymarcon 
drupal-7.59.sql added

**Review by ymarcon — APPROVED** [review]

**Pull request merged**
